### ISSUE TITLE
method `getActualProfile()` seems to be broken

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/meta-test-family#118]
I just executed [test suite](https://github.com/container-images/postfix/pull/11) from postfix and got this error:

```
2017-10-03 09:30:09,705 test             L0240 INFO | START 4-sanity1.py:SanityCheck1.testPostfixSkipped
2017-10-03 09:30:09,721 output           L0655 DEBUG| Module Type: docker - Backend: docker - Profile: default
2017-10-03 09:30:11,250 stacktrace       L0039 ERROR| 
2017-10-03 09:30:11,251 stacktrace       L0042 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:596
2017-10-03 09:30:11,256 stacktrace       L0045 ERROR| Traceback (most recent call last):
2017-10-03 09:30:11,256 stacktrace       L0045 ERROR|   File "/home/tt/g/postfix/tests/sanity1.py", line 53, in testPostfixSkipped
2017-10-03 09:30:11,256 stacktrace       L0045 ERROR|     module_framework.skipTestIf("postfix" not in self.getActualProfile())
2017-10-03 09:30:11,256 stacktrace       L0045 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/avocado_testers/avocado_test.py", line 194, in getActualProfile
2017-10-03 09:30:11,256 stacktrace       L0045 ERROR|     allpackages = self.run(r'rpm -qa --qf="%{{name}}\n"', verbose=is_not_silent()).stdout.split('\n')
2017-10-03 09:30:11,257 stacktrace       L0045 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/avocado_testers/avocado_test.py", line 124, in run
2017-10-03 09:30:11,257 stacktrace       L0045 ERROR|     return self.backend.run(*args, **kwargs)
2017-10-03 09:30:11,257 stacktrace       L0045 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/helpers/container_helper.py", line 207, in run
2017-10-03 09:30:11,257 stacktrace       L0045 ERROR|     **kwargs)
2017-10-03 09:30:11,257 stacktrace       L0045 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/common.py", line 398, in runHost
2017-10-03 09:30:11,257 stacktrace       L0045 ERROR|     return process.run("%s" % formattedcommand, **kwargs)
2017-10-03 09:30:11,257 stacktrace       L0045 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 1117, in run
2017-10-03 09:30:11,257 stacktrace       L0045 ERROR|     raise CmdError(cmd, sp.result)
2017-10-03 09:30:11,257 stacktrace       L0045 ERROR| CmdError: Command 'docker exec 1912aab85c7b1c5c08a3ebf28a94ea2228ba856f385a5b75809401dd4ac09d44 bash -c "rpm -qa --qf=\"%{name}\n\""' failed (rc=1)
2017-10-03 09:30:11,257 stacktrace       L0046 ERROR| 
2017-10-03 09:30:11,258 test             L0601 DEBUG| Local variables:
2017-10-03 09:30:11,321 test             L0604 DEBUG|  -> self <class 'sanity1.SanityCheck1'>: 4-sanity1.py:SanityCheck1.testPostfixSkipped
2017-10-03 09:30:15,562 output           L0655 DEBUG| To run a command inside a container execute: 
2017-10-03 09:30:15,562 output           L0655 DEBUG| docker exec 1912aab85c7b1c5c08a3ebf28a94ea2228ba856f385a5b75809401dd4ac09d44 /bin/bash
2017-10-03 09:30:15,563 test             L0729 ERROR| Traceback (most recent call last):

2017-10-03 09:30:15,563 test             L0729 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/core/test.py", line 667, in _run_avocado
    raise test_exception

2017-10-03 09:30:15,563 test             L0729 ERROR| CmdError: Command 'docker exec 1912aab85c7b1c5c08a3ebf28a94ea2228ba856f385a5b75809401dd4ac09d44 bash -c "rpm -qa --qf=\"%{name}\n\""' failed (rc=1)

2017-10-03 09:30:15,564 test             L0744 ERROR| ERROR 4-sanity1.py:SanityCheck1.testPostfixSkipped -> CmdError: Command 'docker exec 1912aab85c7b1c5c08a3ebf28a94ea2228ba856f385a5b75809401dd4ac09d44 bash -c "rpm -qa --qf=\"%{name}\n\""' failed (rc=1)
2017-10-03 09:30:15,564 test             L0733 INFO | 
2017-10-03 09:30:15,668 sysinfo          L0109 DEBUG| Not logging /proc/pci (file does not exist)
2017-10-03 09:30:15,684 sysinfo          L0107 DEBUG| Not logging /proc/slabinfo (lack of permissions)
2017-10-03 09:30:15,691 sysinfo          L0109 DEBUG| Not logging /sys/kernel/debug/sched_features (file does not exist)
```

```
meta-test-family-0.7.3-1.git.9.b24b28e.fc28.noarch
```

**Comment by jscotka** [comment]
Thats true, we have to repair this method, but this method is more less just stub now, because not easy way, or where to use profiles, so I've filled also: https://github.com/container-images/postfix/issues/15
