### ISSUE TITLE
taskotron error

### ISSUE THREAD

**Issue by jscotka** [fedora-modularity/meta-test-family#130]
there is traceback like:
```
21:51:42 DEBUG| -----------
21:51:42 DEBUG| | EXCEPTION IN: /usr/lib/python2.7/site-packages/moduleframework/helpers/nspawn_helper.py 
21:51:42 DEBUG| | LINE: 256, **kwargs) 
21:51:42 DEBUG| | ERROR: Command 'systemd-run --wait -M bash_1507240297.326002 /bin/bash -c "(/bin/true)>/var/tmp/stdout 2>/var/tmp/stderr " ' failed (rc=1)
21:51:42 DEBUG| -----------
21:51:42 ERROR| 
21:51:42 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:596
21:51:42 ERROR| Traceback (most recent call last):
21:51:42 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/tools/modulelint.py", line 139, in test
21:51:42 ERROR|     self.start()
21:51:42 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/avocado_testers/avocado_test.py", line 110, in start
21:51:42 ERROR|     return self.backend.start(*args, **kwargs)
21:51:42 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/helpers/nspawn_helper.py", line 229, in start
21:51:42 ERROR|     self.__run_systemdrun(command, internal_background=False, ignore_bg_processes=True, verbose=is_debug())
21:51:42 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/helpers/nspawn_helper.py", line 266, in __run_systemdrun
21:51:42 ERROR|     raise CmdExc("Command in SYSTEMD-RUN failed: %s" % command, e)
21:51:42 ERROR| CmdExc: ('EXCEPTION MTF: ', 'TYPE Command', 'Command in SYSTEMD-RUN failed: /bin/true', CmdError())
21:51:42 ERROR| 
21:51:42 DEBUG| Local variables:
21:51:42 DEBUG|  -> self <class 'modulelint.ModuleLintPackagesCheck'>: 13-/usr/lib/python2.7/site-packages/moduleframework/tools/modulelint.py:ModuleLintPackagesCheck.test
21:51:42 DEBUG| 
```
We have to fix it.

There is more reason why this could happen (investigate if it is not running on Fedora-25)
check version of systemd

https://taskotron-dev.fedoraproject.org/artifacts/all/050d76ae-aa17-11e7-bdb7-52540009effe/task_output/avocado-result.modulelint/html/test-results/13-_usr_lib_python2.7_site-packages_moduleframework_tools_modulelint.py:ModuleLintPackagesCheck.test/debug.log

**Comment by jscotka** [comment]
This i already fixed
