### ISSUE TITLE
Errors and false positives from template repo

### ISSUE THREAD

**Issue by TomasTomecek** [fedora-modularity/meta-test-family#142]
First of all, the new dockerfile checks found 2 issues in the template repo! There was no `name` label and the `maintainer` label was defined in caps. Good job!

On the other hand, there was also a bunch of false positives:

- [x] help file was not detected (`COPY` is used, not `ADD`)
  ```
  07:20:02 DEBUG| Dockerfile tag CMD is not parsed by MTF
  07:20:02 ERROR| 
  07:20:02 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:596
  07:20:02 ERROR| Traceback (most recent call last):
  07:20:02 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/tools/dockerlint.py", line 94, in test_helpmd_is_present
  07:20:02 ERROR|     self.assertTrue(self.dp.check_helpmd_is_present())
  07:20:02 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/dockerlinter.py", line 258, in check_helpmd_is_present
  07:20:02 ERROR|     for a in self.docker_dict[ADD]:
  07:20:02 ERROR| KeyError: 'ADD'
  07:20:02 ERROR| 
  07:20:02 DEBUG| Local variables:
  07:20:02 DEBUG|  -> self <class 'dockerlint.DockerFileLinter'>: 14-/usr/lib/python2.7/site-packages/moduleframework/tools/dockerlint.py:DockerFileLinter.test_helpmd_is_present
  07:20:02 DEBUG| 
  ```
- [x] also please provide a nicer error message for the above
- [x] help file of template repo is in roff format #138 
- [x] and if not found, this ugly error is raised:
  ```
  07:20:03 DEBUG| Dockerfile tag CMD is not parsed by MTF
  07:20:03 ERROR| 
  07:20:03 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:596
  07:20:03 ERROR| Traceback (most recent call last):
  07:20:03 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/tools/helpmd_lint.py", line 54, in test_helpmd_image_name
  07:20:03 ERROR|     self.assertTrue(self.helpmd.get_image_name(container_name[0].split('=')[1]))
  07:20:03 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/helpfile_linter.py", line 38, in get_image_name
  07:20:03 ERROR|     tag_exists = [x for x in self.help_md if name.upper() in x]
  07:20:03 ERROR| TypeError: 'NoneType' object is not iterable
  07:20:03 ERROR| 
  07:20:03 DEBUG| Local variables:
  07:20:03 DEBUG|  -> self <class 'helpmd_lint.HelpMDLinter'>: 17-/usr/lib/python2.7/site-packages/moduleframework/tools/helpmd_lint.py:HelpMDLinter.test_helpmd_image_name
  07:20:03 DEBUG|  -> container_name <type 'list'>: [u'NAME=mycontainer']
  07:20:03 DEBUG| 
  ```
- [x] almost all help file-related checks are broken:
  ```
  07:20:04 DEBUG| Dockerfile tag CMD is not parsed by MTF
  07:20:04 ERROR| 
  07:20:04 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:596
  07:20:04 ERROR| Traceback (most recent call last):
  07:20:04 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/tools/helpmd_lint.py", line 79, in test_helpmd_security_implications
  07:20:04 ERROR|     self.assertTrue(self.helpmd.get_tag("SECURITY IMPLICATIONS"))
  07:20:04 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/helpfile_linter.py", line 48, in get_tag
  07:20:04 ERROR|     tag_exists = [x for x in self.help_md if name.upper() in x]
  07:20:04 ERROR| TypeError: 'NoneType' object is not iterable
  07:20:04 ERROR| 
  07:20:04 DEBUG| Local variables:
  07:20:04 DEBUG|  -> self <class 'helpmd_lint.HelpMDLinter'>: 23-/usr/lib/python2.7/site-packages/moduleframework/tools/helpmd_lint.py:HelpMDLinter.test_helpmd_security_implications
  07:20:04 DEBUG| 
  ```
- [x] There is something wrong with the rpm-related checks (I hope that conu will help with this one):
  ```
  07:20:06 INFO | Running 'docker exec 9388d8d36cffd227c4ff59e5dca1df6c8d7f9cf140c3b119944758ecaae88f17 bash -c "rpm -qa --qf=\"%{name}\n\""'
  07:20:06 DEBUG| [stderr] RPM version 4.13.0.1
  07:20:06 DEBUG| [stderr] Copyright (C) 1998-2002 - Red Hat, Inc.
  07:20:06 DEBUG| [stderr] This program may be freely redistributed under the terms of the GNU GPL
  07:20:06 DEBUG| [stderr] 
  07:20:06 DEBUG| [stderr] Usage: rpm [-afgpcdLlsiv?] [-a|--all] [-f|--file] [-g|--group]
  07:20:06 DEBUG| [stderr]         [-p|--package] [--pkgid] [--hdrid] [--triggeredby] [--whatrequires]
  07:20:06 DEBUG| [stderr]         [--whatprovides] [--whatrecommends] [--whatsuggests]
  07:20:06 DEBUG| [stderr]         [--whatsupplements] [--whatenhances] [--nomanifest]
  07:20:06 DEBUG| [stderr]         [-c|--configfiles] [-d|--docfiles] [-L|--licensefiles] [--dump]
  07:20:06 DEBUG| [stderr]         [-l|--list] [--queryformat=QUERYFORMAT] [-s|--state]
  07:20:06 DEBUG| [stderr]         [--nofiledigest] [--nofiles] [--nodeps] [--noscript] [--allfiles]
  07:20:06 DEBUG| [stderr]         [--allmatches] [--badreloc] [-e|--erase=<package>+] [--excludedocs]
  07:20:06 DEBUG| [stderr]         [--excludepath=<path>] [--force] [-F|--freshen=<packagefile>+]
  07:20:06 DEBUG| [stderr]         [-h|--hash] [--ignorearch] [--ignoreos] [--ignoresize]
  07:20:06 DEBUG| [stderr]         [-i|--install] [--justdb] [--nodeps] [--nofiledigest]
  07:20:06 DEBUG| [stderr]         [--nocontexts] [--noorder] [--noscripts] [--notriggers]
  07:20:06 DEBUG| [stderr]         [--oldpackage] [--percent] [--prefix=<dir>] [--relocate=<old>=<new>]
  07:20:06 DEBUG| [stderr]         [--replacefiles] [--replacepkgs] [--test]
  07:20:06 DEBUG| [stderr]         [-U|--upgrade=<packagefile>+] [--reinstall=<packagefile>+]
  07:20:06 DEBUG| [stderr]         [-D|--define='MACRO EXPR'] [--undefine=MACRO] [-E|--eval='EXPR']
  07:20:06 DEBUG| [stderr]         [--macros=<FILE:...>] [--noplugins] [--nodigest] [--nosignature]
  07:20:06 DEBUG| [stderr]         [--rcfile=<FILE:...>] [-r|--root=ROOT] [--dbpath=DIRECTORY]
  07:20:06 DEBUG| [stderr]         [--querytags] [--showrc] [--quiet] [-v|--verbose] [--version]
  07:20:06 DEBUG| [stderr]         [-?|--help] [--usage] [--scripts] [--setperms] [--setugids]
  07:20:06 DEBUG| [stderr]         [--conflicts] [--obsoletes] [--provides] [--requires]
  07:20:06 DEBUG| [stderr]         [--recommends] [--suggests] [--supplements] [--enhances] [--info]
  07:20:06 DEBUG| [stderr]         [--changelog] [--xml] [--triggers] [--filetriggers] [--last]
  07:20:06 DEBUG| [stderr]         [--dupes] [--filesbypkg] [--fileclass] [--filecolor] [--fscontext]
  07:20:06 DEBUG| [stderr]         [--fileprovide] [--filerequire] [--filecaps]
  07:20:06 INFO | Command 'docker exec 9388d8d36cffd227c4ff59e5dca1df6c8d7f9cf140c3b119944758ecaae88f17 bash -c "rpm -qa --qf=\"%{name}\n\""' finished with 1 after 0.0744640827179s
  07:20:06 ERROR| 
  07:20:06 ERROR| Reproduced traceback from: /usr/lib/python2.7/site-packages/avocado/core/test.py:596
  07:20:06 ERROR| Traceback (most recent call last):
  07:20:06 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/tools/modulelint.py", line 63, in test
  07:20:06 ERROR|     for x in self.run(r'rpm -qa --qf="%{{name}}\n"').stdout.split('\n')]
  07:20:06 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/avocado_testers/avocado_test.py", line 134, in run
  07:20:06 ERROR|     return self.backend.run(*args, **kwargs)
  07:20:06 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/helpers/container_helper.py", line 203, in run
  07:20:06 ERROR|     **kwargs)
  07:20:06 ERROR|   File "/usr/lib/python2.7/site-packages/moduleframework/common.py", line 400, in runHost
  07:20:06 ERROR|     return process.run("%s" % formattedcommand, **kwargs)
  07:20:06 ERROR|   File "/usr/lib/python2.7/site-packages/avocado/utils/process.py", line 1117, in run
  07:20:06 ERROR|     raise CmdError(cmd, sp.result)
  07:20:06 ERROR| CmdError: Command 'docker exec 9388d8d36cffd227c4ff59e5dca1df6c8d7f9cf140c3b119944758ecaae88f17 bash -c "rpm -qa --qf=\"%{name}\n\""' failed (rc=1)
  07:20:06 ERROR| 
  07:20:06 DEBUG| Local variables:
  07:20:06 DEBUG|  -> self <class 'modulelint.ModuleLintPackagesCheck'>: 24-/usr/lib/python2.7/site-packages/moduleframework/tools/modulelint.py:ModuleLintPackagesCheck.test
  07:20:06 DEBUG| 
  ```

**Comment by phracek** [comment]
First instruction was fixed by commit https://github.com/fedora-modularity/meta-test-family/commit/b9d16763a39d7a14cc7647e07e82b032ee89cc0f

**Comment by phracek** [comment]
4th and 5th comment are fixed by PR #144.
4th should be be already fixed by commit https://github.com/fedora-modularity/meta-test-family/commit/e20ba7afda8e97551e6bc8f71716d58316269ab1

**Comment by TomasTomecek** [comment]
Feel free to edit my post and cross items which were fixed.

**Comment by phracek** [comment]
One more issue detected https://github.com/fedora-modularity/meta-test-family/pull/154

**Comment by phracek** [comment]
All issues were addressed. Closing it for now.
