### ISSUE TITLE
Fail in testDockerFromBaseruntime: FAIL - how to debug?

### ISSUE THREAD

**Issue by bkabrda** [fedora-modularity/meta-test-family#45]
Hi, I have a following Dockerfile:

```
FROM registry.fedoraproject.org/fedora:26

LABEL MAINTAINER ...

ENV NAME=mycontainer VERSION=0 RELEASE=1 ARCH=x86_64

LABEL summary="A container that tells you how awesome it is." \
      com.redhat.component="$NAME" \
      version="$VERSION" \
      release="$RELEASE.$DISTTAG" \
      architecture="$ARCH" \
      usage="docker run -p 9000:9000 mycontainer" \
      help="Runs mycontainer, which listens on port 9000 and tells you how awesome it is. No dependencies." \
      description="This is a simple container that just tells you how awesome it is. That's it." \
      vendor="Fedora Project" \
      org.fedoraproject.component="postfix" \
      authoritative-source-url="some.url.org" \
      io.k8s.description="This is a simple container that just tells you how awesome it is. That's it." \
      io.k8s.display-name="Awesome container with SW version 2.4" \
      io.openshift.expose-services="9000:http" \
      io.openshift.tags="some,tags"

EXPOSE 9000

# We don't actually use the "software_version" here, but we could,
#  e.g. to install a module with that ncat version
RUN dnf install -y nmap-ncat && \
    dnf clean all

# add help file
COPY root /
COPY script.sh /usr/bin/

CMD ["/usr/bin/script.sh"]
```

When running tests on it via MTF, I'm getting following failure:

```
(04/18) /usr/share/moduleframework/tools/modulelint/modulelint.py:DockerfileLinter.testDockerFromBaseruntime: FAIL (0.03 s)
```

The logs say this:

```
2017-08-11 08:41:40,700 test             L0240 INFO | START 04-/usr/share/moduleframework/tools/modulelint/modulelint.py:DockerfileLinter.testDockerFromBaseruntime
2017-08-11 08:41:40,717 output           L0655 DEBUG| Module Type: docker; Profile: default
2017-08-11 08:41:40,741 output           L0655 DEBUG| Dockerfile tag COPY is not parsed by MTF
2017-08-11 08:41:40,741 output           L0655 DEBUG| Dockerfile tag COPY is not parsed by MTF
2017-08-11 08:41:40,741 output           L0655 DEBUG| Dockerfile tag CMD is not parsed by MTF
2017-08-11 08:41:40,741 stacktrace       L0039 ERROR|
2017-08-11 08:41:40,741 stacktrace       L0042 ERROR| Reproduced traceback from: /home/bkabrda/.local/lib/python2.7/site-packages/avocado/core/test.py:596
2017-08-11 08:41:40,742 stacktrace       L0045 ERROR| Traceback (most recent call last):
2017-08-11 08:41:40,743 stacktrace       L0045 ERROR|   File "/usr/share/moduleframework/tools/modulelint/modulelint.py", line 48, in testDockerFromBaseruntime
2017-08-11 08:41:40,743 stacktrace       L0045 ERROR|     self.assertTrue(self.dp.check_baseruntime())
2017-08-11 08:41:40,743 stacktrace       L0045 ERROR|   File "/usr/lib64/python2.7/unittest/case.py", line 460, in assertTrue
2017-08-11 08:41:40,743 stacktrace       L0045 ERROR|     raise self.failureException(msg)
2017-08-11 08:41:40,743 stacktrace       L0045 ERROR| AssertionError: [] is not true
2017-08-11 08:41:40,743 stacktrace       L0046 ERROR|
2017-08-11 08:41:40,743 test             L0601 DEBUG| Local variables:
2017-08-11 08:41:40,773 test             L0604 DEBUG|  -> self <class 'modulelint.DockerfileLinter'>: 04-/usr/share/moduleframework/tools/modulelint/modulelint.py:DockerfileLinter.testDockerFromBaseruntime
2017-08-11 08:41:40,773 test             L0744 ERROR| FAIL 04-/usr/share/moduleframework/tools/modulelint/modulelint.py:DockerfileLinter.testDockerFromBaseruntime -> AssertionError: [] is not true
```

As a user of MTF, I have no idea

1. What I did wrong
2. How to debug it
3. When debugging, how to run only this specific test to speed things up

This is probably just a bug, but in addition to fixing it (which is kind of point 1.), it'd be great to have points 2. and 3. documented.

**Comment by bkabrda** [comment]
FTR, I'm using MTF version 0.5.18 installed as RPM from https://copr.fedorainfracloud.org/coprs/phracek/meta-test-family/

**Comment by phracek** [comment]
The baseruntime check will be remove.
