### ISSUE TITLE
MTF should work without "rpm" module

### ISSUE THREAD

**Issue by bkabrda** [fedora-modularity/meta-test-family#46]
Hi, I have a `config.yaml` like this:

```
document: modularity-testing
version: 1
name: myawesomecontainer
service:
  port: 9000
packages:
  rpms:
    - nmap-ncat
module:
    docker:
      start: "docker run -d -p 9000:9000"
    rpm:
      repo: <something>
```

I only care about testing the `docker` module. When I remove it, avocado fails and the following error is in the log file:

```
2017-08-11 09:12:45,925 test             L0240 INFO | START 01-sanity1.py:SanityCheck1.test1
2017-08-11 09:12:45,931 output           L0655 DEBUG| Process Process-1:
2017-08-11 09:12:45,931 output           L0655 DEBUG| Traceback (most recent call last):
2017-08-11 09:12:45,931 output           L0655 DEBUG|   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
2017-08-11 09:12:45,931 output           L0655 DEBUG|     self.run()
2017-08-11 09:12:45,931 output           L0655 DEBUG|   File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
2017-08-11 09:12:45,931 output           L0655 DEBUG|     self._target(*self._args, **self._kwargs)
2017-08-11 09:12:45,931 output           L0655 DEBUG|   File "/home/bkabrda/.local/lib/python2.7/site-packages/avocado/core/runner.py", line 325, in _run_test
2017-08-11 09:12:45,932 output           L0655 DEBUG|     instance = loader.load_test(test_factory)
2017-08-11 09:12:45,932 output           L0655 DEBUG|   File "/home/bkabrda/.local/lib/python2.7/site-packages/avocado/core/loader.py", line 338, in load_test
2017-08-11 09:12:45,932 output           L0655 DEBUG|     test_instance = test_class(**test_parameters)
2017-08-11 09:12:45,932 output           L0655 DEBUG|   File "/home/bkabrda/.local/lib/python2.7/site-packages/moduleframework/module_framework.py", line 1101, in __init__
2017-08-11 09:12:45,932 output           L0655 DEBUG|     (self.backend, self.moduleType) = get_correct_backend()
2017-08-11 09:12:45,932 output           L0655 DEBUG|   File "/home/bkabrda/.local/lib/python2.7/site-packages/moduleframework/module_framework.py", line 1352, in get_correct_backend
2017-08-11 09:12:45,932 output           L0655 DEBUG|     readconfig.loadconfig()
2017-08-11 09:12:45,932 output           L0655 DEBUG|   File "/home/bkabrda/.local/lib/python2.7/site-packages/moduleframework/module_framework.py", line 146, in loadconfig
2017-08-11 09:12:45,933 output           L0655 DEBUG|     'source') else self.config['module']['rpm'].get('source')
2017-08-11 09:12:45,933 output           L0655 DEBUG| KeyError: 'rpm'
```

I think it should be possible to omit the `rpm` module, hence I think this is a bug.

**Comment by TomasTomecek** [comment]
It would be awesome if MTF supported a use case when users want to test just containers (based on modules or not). Not sure if it made sense to have the use case defined in the config file (or the `MODULE` env var is the thing).

Anyway, I agree with Slavek here, if some config key is omitted, it would be awesome if the selected functionality would be just turned off.

**Comment by jscotka** [comment]
working on that in https://github.com/jscotka/meta-test-family/tree/module_type_split

**Comment by jscotka** [comment]
It is in devel branch
